# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

StandardizeInterbeefResults_main <- function(paramFileName) {
    .Call(`_StandardizeInterbeefResults_StandardizeInterbeefResults_main`, paramFileName)
}

rcpp_hello <- function() {
    .Call(`_StandardizeInterbeefResults_rcpp_hello`)
}

